name: portfolio
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  font_awesome_flutter: ^10.7.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Console
      fonts:
        - asset: assets/fonts/Inconsolata-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inconsolata-Black.ttf
          weight: 900
        - asset: assets/fonts/Inconsolata-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inconsolata-Light.ttf
          weight: 300
        - asset: assets/fonts/Inconsolata-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inconsolata-SemiBold.ttf
          weight: 600
